### ISSUE TITLE
Why Zanata only allow English as the source language?

### ISSUE THREAD

**Issue by fishfree** [zanata/fake-zanata-server#17]
I'm sorry to post this question here, for I found nowhere to ask. How can I set other arbitrary language as the source language?

**Comment by carlosmunoz** [comment]
Hi @fishfree, you can always send an email to our mailing lists (http://zanata.org/mailing-lists/) or use our IRC channel (http://webchat.freenode.net/?channels=zanata) to communicate.

As to your specific question, there is a way to upload source documents in other languages. There is an option in the command line client (`--src-lang`) which lets you specify the source language when pushing source documents. For more info you can use the command line clinet like this: `zanata-cli help push`
